### ISSUE TITLE
Guava dependancy conflict

### ISSUE THREAD

**Issue by dwilliams-gs** [AutomatedOwl/allure-enivonment-writer#4]
### Description of issue

When upgrading our version of `selenium-java` to `4.1.2` we see the following issue due to a conflict in the dependancy version of Guava used within the dependancy.

```
java.lang.NoSuchMethodError: com.google.common.collect.ImmutableMap.of(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Lcom/google/common/collect/ImmutableMap;
	at org.openqa.selenium.chrome.AddHasCasting.getAdditionalCommands(AddHasCasting.java:38)
	at org.openqa.selenium.chrome.ChromeDriver$ChromeDriverCommandExecutor.getExtraCommands(ChromeDriver.java:123)
	at org.openqa.selenium.chrome.ChromeDriver$ChromeDriverCommandExecutor.<init>(ChromeDriver.java:118)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:106)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:93)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:82)
```

#### Interim fix

Adding an exclusion onto the dependancy within the pom.xml

```
        <dependency>
            <groupId>com.github.automatedowl</groupId>
            <artifactId>allure-environment-writer</artifactId>
            <version>1.0.0</version>
            <exclusions>
                <exclusion>
                    <groupId>com.google.guava</groupId>
                    <artifactId>guava</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

####  Fix

- Bump the version of Guava for the dependancy from `29.0-jre` -> `31.0.1-jre`
- Remove the need for the Guava dependancy

#### Info

- https://stackoverflow.com/questions/50172479/java-lang-noclassdeffounderror-com-google-common-collect-immutablemap-while-usi/70969932#70969932
- https://github.com/bonigarcia/webdrivermanager/issues/779

**Comment by AutomatedOwl** [comment]
Thanks a lot for opening the issue. Currently i'm in a super-busy days at work. Would really appreciate if you or another member can open PR accordingly. Anyways, will try to reach it ASAP. @dwilliams-gs

**Comment by AutomatedOwl** [comment]
Please try with the newly released version
